<?php


$GLOBALS['ROOT'] = $_SERVER['DOCUMENT_ROOT'];


// MODIFICAR SEGÚN TENGAS EL PROYECTO GUARDADO LOCALMENTE
$PROYECTO = 'GitHub/TPS-PWA/TPS-PWA';

// ALMACENA EL DIRECTORIO DEL PROYECTO
$ROOT = $_SERVER['DOCUMENT_ROOT']."/$PROYECTO/";


?>